"use strict";
exports.__esModule = true;
exports.NodeType = void 0;
exports.NodeType = {
    AdditiveExpression: "AdditiveExpression",
    MultiplicativeExpression: "MultiplicativeExpression",
    PrimaryExpression: "PrimaryExpression",
    ParanthesizedExpression: "ParanthesizedExpression",
    IdentifierExpression: "IdentifierExpression",
    AssignmentExpression: "AssignmentExpression",
    BinaryExpression: "BinaryExpression",
    LogicalExpression: "LogicalExpression",
    LogicalANDExpression: "LogicalANDExpression",
    LogicalORExpression: "LogicalORExpression",
    RelationalExpression: "RelationalExpression",
    EqualityExpression: "EqualityExpression",
    BlockStatement: "BlockStatement",
    EmptyStatement: "EmptyStatement",
    ExpressionStatement: "ExpressionStatement",
    InitStatement: "InitStatement",
    PrintStatement: "PrintStatement",
    IfStatement: "IfStatement",
    WhileStatement: "WhileStatement",
    BreakStatement: "BreakStatement",
    ContinueStatement: "ContinueStatement",
    VariableStatement: "VariableStatement",
    BooleanLiteral: "BooleanLiteral",
    NumericLiteral: "NumericLiteral",
    StringLiteral: "StringLiteral",
    NullLiteral: "NullLiteral",
    VariableDeclaration: "VariableDeclaration",
    Program: "Program",
    SleepStatement: "SleepStatement",
    TryCatchStatement: "TryCatchStatement",
    ArrayExpression: "ArrayExpression",
    MemberExpression: "MemberExpression",
    CallExpression: "CallExpression",
    ClassDeclaration: "ClassDeclaration",
    SwitchStatement: "SwitchStatement",
    SwitchCase: "SwitchCase",
    NewExpression: "NewExpression",
    ThisExpression: "ThisExpression"
};
