"use strict";
exports.__esModule = true;
exports.SPEC = exports.TokenTypes = void 0;
exports.TokenTypes = {
    NULL_TYPE: null,
    CHUGLI: "chugli",
    CLASS: "khandaan",
    EXTENDS: "ka_khoon_hai",
    NEW: "avtaar",
    THIS: "khud",
    CONSTRUCTOR: "sanskar",
    SWITCH: "rishtedaar_aaye",
    CASE: "muh_dikhai",
    DEFAULT: "bache_kuche",
    ASYNC: "dheere_dheere",
    AWAIT: "ruko_zara",
    HI_BHAI_TYPE: "idhar aao",
    BYE_BHAI_TYPE: "jao padhai karo",
    BOL_BHAI_TYPE: "jawab de",
    BHAI_YE_HAI_TYPE: "ye sambhal",
    AGAR_BHAI: "agar sharam hai",
    WARNA_BHAI: "warna belt",
    PARAMPARA: "parampara",
    NAHI_TO_BHAI: "nahi to bhai",
    JAB_TAK_BHAI: "jab tak main na bolu",
    BAS_KAR_BHAI: "bas kar bhai",
    AGLA_DEKH_BHAI: "agla dekh bhai",
    NALLA_TYPE: "NALLA",
    SEMI_COLON_TYPE: ";",
    OPEN_CURLY_BRACE_TYPE: "{",
    CLOSED_CURLY_BRACE_TYPE: "}",
    OPEN_PARENTHESIS_TYPE: "(",
    CLOSED_PARENTHESIS_TYPE: ")",
    COMMA_TYPE: ",",
    OPEN_SQUARE_BRACKET: "[",
    CLOSED_SQUARE_BRACKET: "]",
    DOT: ".",
    COLON_TYPE: ":",
    NUMBER_TYPE: "NUMBER",
    IDENTIFIER_TYPE: "IDENTIFIER",
    SIMPLE_ASSIGN_TYPE: "SIMPLE_ASSIGN",
    COMPLEX_ASSIGN_TYPE: "COMPLEX_ASSIGN",
    ADDITIVE_OPERATOR_TYPE: "ADDITIVE_OPERATOR",
    MULTIPLICATIVE_OPERATOR_TYPE: "MULTIPLICATIVE_OPERATOR",
    RELATIONAL_OPERATOR: "RELATIONAL_OPERATOR",
    EQUALITY_OPERATOR: "EQUALITY_OPERATOR",
    STRING_TYPE: "STRING",
    BOOLEAN_TYPE: "BOOLEAN",
    LOGICAL_AND: "LOGICAL_AND",
    LOGICAL_OR: "LOGICAL_OR",
    TRY: "chori chuppe",
    CATCH: "pakde gaye toh",
    SLEEP: "bas paanch minute"
};
exports.SPEC = [
    // Whitespcaes
    { regex: /^\s+/, tokenType: exports.TokenTypes.NULL_TYPE },
    // singke line Comments
    { regex: /^\/\/.*/, tokenType: exports.TokenTypes.NULL_TYPE },
    { regex: /^\bchugli:.*/, tokenType: exports.TokenTypes.NULL_TYPE },
    // multi line comments
    { regex: /^\/\*[\s\S]*?\*\//, tokenType: exports.TokenTypes.NULL_TYPE },
    // Symbols, delimiters
    { regex: /^;/, tokenType: exports.TokenTypes.SEMI_COLON_TYPE },
    { regex: /^\{/, tokenType: exports.TokenTypes.OPEN_CURLY_BRACE_TYPE },
    { regex: /^\}/, tokenType: exports.TokenTypes.CLOSED_CURLY_BRACE_TYPE },
    { regex: /^\(/, tokenType: exports.TokenTypes.OPEN_PARENTHESIS_TYPE },
    { regex: /^\)/, tokenType: exports.TokenTypes.CLOSED_PARENTHESIS_TYPE },
    { regex: /^,/, tokenType: exports.TokenTypes.COMMA_TYPE },
    { regex: /^\[/, tokenType: exports.TokenTypes.OPEN_SQUARE_BRACKET },
    { regex: /^\]/, tokenType: exports.TokenTypes.CLOSED_SQUARE_BRACKET },
    { regex: /^\./, tokenType: exports.TokenTypes.DOT },
    { regex: /^:/, tokenType: exports.TokenTypes.COLON_TYPE },
    //Keywords
    { regex: /^\bidhar aao\b/, tokenType: exports.TokenTypes.HI_BHAI_TYPE },
    { regex: /^\bjao padhai karo\b/, tokenType: exports.TokenTypes.BYE_BHAI_TYPE },
    { regex: /^\bjawab de\b/, tokenType: exports.TokenTypes.BOL_BHAI_TYPE },
    { regex: /^\bye sambhal\b/, tokenType: exports.TokenTypes.BHAI_YE_HAI_TYPE },
    { regex: /^\bagar sharam hai\b/, tokenType: exports.TokenTypes.AGAR_BHAI },
    { regex: /^\bnahi to bhai\b/, tokenType: exports.TokenTypes.NAHI_TO_BHAI },
    { regex: /^\bwarna belt\b/, tokenType: exports.TokenTypes.WARNA_BHAI },
    { regex: /^\bparampara\b/, tokenType: exports.TokenTypes.PARAMPARA },
    { regex: /^\bkhandaan\b/, tokenType: exports.TokenTypes.CLASS },
    { regex: /^\bka_khoon_hai\b/, tokenType: exports.TokenTypes.EXTENDS },
    { regex: /^\bavtaar\b/, tokenType: exports.TokenTypes.NEW },
    { regex: /^\bkhud\b/, tokenType: exports.TokenTypes.THIS },
    { regex: /^\bsanskar\b/, tokenType: exports.TokenTypes.CONSTRUCTOR },
    { regex: /^\brishtedaar_aaye\b/, tokenType: exports.TokenTypes.SWITCH },
    { regex: /^\bmuh_dikhai\b/, tokenType: exports.TokenTypes.CASE },
    { regex: /^\bbache_kuche\b/, tokenType: exports.TokenTypes.DEFAULT },
    { regex: /^\bdheere_dheere\b/, tokenType: exports.TokenTypes.ASYNC },
    { regex: /^\bruko_zara\b/, tokenType: exports.TokenTypes.AWAIT },
    { regex: /^\bkhaali_dimaag\b/, tokenType: exports.TokenTypes.NALLA_TYPE },
    { regex: /^\bjab tak main na bolu\b/, tokenType: exports.TokenTypes.JAB_TAK_BHAI },
    { regex: /^\bbas kar bhai\b/, tokenType: exports.TokenTypes.BAS_KAR_BHAI },
    { regex: /^\bagla dekh bhai\b/, tokenType: exports.TokenTypes.AGLA_DEKH_BHAI },
    { regex: /^\bchori chuppe\b/, tokenType: exports.TokenTypes.TRY },
    { regex: /^\bpakde gaye toh\b/, tokenType: exports.TokenTypes.CATCH },
    { regex: /^\bbas paanch minute\b/, tokenType: exports.TokenTypes.SLEEP },
    // Number
    { regex: /^[+-]?([\d]*[.])?[\d]+/, tokenType: exports.TokenTypes.NUMBER_TYPE },
    // Boolean
    { regex: /^\bsharmaji_ka_beta\b/, tokenType: exports.TokenTypes.BOOLEAN_TYPE },
    { regex: /^\bnalayak\b/, tokenType: exports.TokenTypes.BOOLEAN_TYPE },
    // Identifier
    { regex: /^\w+/, tokenType: exports.TokenTypes.IDENTIFIER_TYPE },
    // Equality operator: ==, !=
    { regex: /^[=!]=/, tokenType: exports.TokenTypes.EQUALITY_OPERATOR },
    // Assignment operators: =, *=, /=, +=, -=
    { regex: /^=/, tokenType: exports.TokenTypes.SIMPLE_ASSIGN_TYPE },
    { regex: /^[\*\%\/\+\-]=/, tokenType: exports.TokenTypes.COMPLEX_ASSIGN_TYPE },
    // operator
    { regex: /^[+\-]/, tokenType: exports.TokenTypes.ADDITIVE_OPERATOR_TYPE },
    { regex: /^[*\/\%]/, tokenType: exports.TokenTypes.MULTIPLICATIVE_OPERATOR_TYPE },
    { regex: /^[><]=?/, tokenType: exports.TokenTypes.RELATIONAL_OPERATOR },
    // logical operators: &&, ||
    { regex: /^&&/, tokenType: exports.TokenTypes.LOGICAL_AND },
    { regex: /^\|\|/, tokenType: exports.TokenTypes.LOGICAL_OR },
    // String
    { regex: /^"[^"]*"/, tokenType: exports.TokenTypes.STRING_TYPE },
    { regex: /^'[^']*'/, tokenType: exports.TokenTypes.STRING_TYPE },
];
