export declare const TokenTypes: {
    NULL_TYPE: null;
    CHUGLI: string;
    CLASS: string;
    EXTENDS: string;
    NEW: string;
    THIS: string;
    CONSTRUCTOR: string;
    SWITCH: string;
    CASE: string;
    DEFAULT: string;
    ASYNC: string;
    AWAIT: string;
    HI_BHAI_TYPE: string;
    BYE_BHAI_TYPE: string;
    BOL_BHAI_TYPE: string;
    BHAI_YE_HAI_TYPE: string;
    AGAR_BHAI: string;
    WARNA_BHAI: string;
    PARAMPARA: string;
    NAHI_TO_BHAI: string;
    JAB_TAK_BHAI: string;
    BAS_KAR_BHAI: string;
    AGLA_DEKH_BHAI: string;
    NALLA_TYPE: string;
    SEMI_COLON_TYPE: string;
    OPEN_CURLY_BRACE_TYPE: string;
    CLOSED_CURLY_BRACE_TYPE: string;
    OPEN_PARENTHESIS_TYPE: string;
    CLOSED_PARENTHESIS_TYPE: string;
    COMMA_TYPE: string;
    OPEN_SQUARE_BRACKET: string;
    CLOSED_SQUARE_BRACKET: string;
    DOT: string;
    COLON_TYPE: string;
    NUMBER_TYPE: string;
    IDENTIFIER_TYPE: string;
    SIMPLE_ASSIGN_TYPE: string;
    COMPLEX_ASSIGN_TYPE: string;
    ADDITIVE_OPERATOR_TYPE: string;
    MULTIPLICATIVE_OPERATOR_TYPE: string;
    RELATIONAL_OPERATOR: string;
    EQUALITY_OPERATOR: string;
    STRING_TYPE: string;
    BOOLEAN_TYPE: string;
    LOGICAL_AND: string;
    LOGICAL_OR: string;
    TRY: string;
    CATCH: string;
    SLEEP: string;
};
export declare const SPEC: ({
    regex: RegExp;
    tokenType: null;
} | {
    regex: RegExp;
    tokenType: string;
})[];
export type Spec = typeof SPEC;
//# sourceMappingURL=dadLangSpec.d.ts.map